image: cprov/stoq:candidate

variables:
  GIT_SUBMODULE_STRATEGY: recursive

stages:
  - test
  - build

before_script:
  # Install tools to create debian packages
  - apt update
  - apt --yes install devscripts debhelper python3-all

test:
  stage: test
  script:
    - make check

.create_deb:
  stage: build
  script:
    - rm -rf dist
    - make deb
  artifacts:
    paths:
      - dist/*.deb

create_deb_master:
  extends: .create_deb
  only:
    - master

create_deb_manual:
  extends: .create_deb
  when: manual
